## LAB 7
### 1. Implement all the built -in functions of numpy with documentation for each function.

#### Funcitons for Array creation

In [7]:
import numpy as np

# .array() - To create a numpy array from list - np.array([List]) 
array = np.array([1,2,3,4,5])
print("Given array :",array)

# .zeros() - To create a 1D zero array of given element - np.zeros(number_of_element)
array_zero = np.zeros(5)
print("Given array :",array_zero)

# .ones() - To create 1D array of given element with value  1 - np.ones(number_of_element)
array_one = np.ones(5)
print("Given array :",array_one)

# .arange() - To create 1D array from range start to stop-1 - np.arange(start,stop,step)
array_range = np.arange(1,11,1)
print("Given arrray of range :",array_range)

# .linspace() - To create 1D equally spaced array between two points 
# - np.linspace(interval_start,interval_stop,number_of_elements)
array_equal_space = np.round(np.linspace(0,1,10),2)
print("Given equally spaced array :",array_equal_space)





Given array : [1 2 3 4 5]
Given array : [0. 0. 0. 0. 0.]
Given array : [1. 1. 1. 1. 1.]
Given arrray of range : [ 1  2  3  4  5  6  7  8  9 10]
Given equally spaced array : [0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


#### Functions for array manupulation

In [25]:
# .reshape() - To change order of matrix - np.reshape(row,column)
elements = np.arange(1,10,1)
matrix = elements.reshape(3,3)
print("Given matrix:\n",matrix)

# .resize() - To change order of matrix, if not enough element then pads zero
# -np.resize(row,column)
elements = np.array([1,2,3,4,5])
matrix = elements.copy()
matrix.resize(5,5)
print("Given matrix:\n",matrix)

# .flatten() - To convert matrix to 1D array, returns copy - matrix_name.flatten()
matrix = np.array([[1,2],
                   [3,4]])
array_1D = matrix.flatten()
print("Given array :",array_1D)

# .ravel() - To convert matrix to 1D array, returns view - matrix_name.ravel()
matrix = np.array([[1,2],
                   [3,4]])
array_1D = matrix.ravel()
print("Given array :",array_1D)

# .transpose() - To transpose the matrix - np.transpose(matrix_name)
matrix = np.array([[1,2],
                   [3,4]])
transpose = np.transpose(matrix)
print("Tranpose matrix :\n",transpose)


Given matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Given matrix:
 [[1 2 3 4 5]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Given array : [1 2 3 4]
Given array : [1 2 3 4]
Tranpose matrix :
 [[1 3]
 [2 4]]


#### Functions for Maths and Statistics

In [30]:
# .mean() - To find mean - np.mean()
array = np.array([1,2,3,4,5])
print("Mean :",np.mean(array))

# .median() - To find median - np.median()
array = np.array([1,2,3,4,5])
print("Median :",np.median(array))

# .std() - To find standard deviation - np.std()
array = np.array([1,2,3,4,5])
print("Standard deviation :",round(np.std(array),3))

# .var() - To find variance - np.var()
array = np.array([1,2,3,4,5])
print("Variance :",np.var(array))

# .max() - To find max - np.max()
array = np.array([1,2,3,4,5])
print("Max :",np.max(array))

# .min() - To find min - np.min()
array = np.array([1,2,3,4,5])
print("Min :",np.min(array))



Mean : 3.0
Median : 3.0
Standard deviation : 1.414
Variance : 2.0
Max : 5
Min : 1


#### Functions for linear algebra

In [36]:
# .solve() - To solve linear equations - np.linalg.solve(variable_matrix,constant_matrix)
# For equation 5x + 4y = 10 and 3x + 7y = 20
v_matrix = np.array([[5,4],
                     [3,7]])
c_matrix = np.array([10,20])
x,y = np.linalg.solve(v_matrix,c_matrix)
print(f"X : {x} and Y : {y} ")

# .inv() - To find inverse of matrix - np.linalg.inv(matrix)
matrix = np.array([[1,2],
                   [3,4]])
print("Inverse matrix :\n",np.linalg.inv(matrix))

# .det() - To find determinant of matrix - np.linalg.det(matrix)
matrix = np.array([[1,2],
                   [3,4]])
print("Determinant :",round(np.linalg.det(matrix),3))



X : -0.43478260869565233 and Y : 3.0434782608695654 
Inverse matrix :
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant : -2.0


#### 2. Execute all the examples in: https://numpy.org/doc/stable/user/quickstart.html

In [35]:
import numpy as np

print("\n---\n")

array = np.arange(15).reshape(3,5)
print("Given matrix :\n",array)
print("Type :",type(array))

print("\n---\n")

array = np.array([1,2,3,4,5])
print("Given array :",array)
print("Data type :",array.dtype)
array = np.array([1.5,3.5])
print("Given array :",array)
print("Data type :",array.dtype)

print("\n---\n")

array = np.linspace(0,2,10)
print("Given angles :",np.round(array,2))
print("Sin values :",np.round(np.sin(array),2))

print("\n---\n")

array = np.arange(6)
print("1D :",array)
print("2D :\n",array.reshape(2,3))
print("3D :\n",array.reshape(1,2,3))

print("\n---\n")

matrxi_A = np.array([[1,2],
                     [3,4]])
matrxi_B = np.array([[1,2],
                     [3,4]])
print("Addition element-wise :\n",matrxi_A + matrxi_B)
print("Multiplication element-wise :\n",matrxi_A * matrxi_B)
print("Multiplication matrix :\n",matrxi_A @ matrxi_B)
print("Division element-wise :\n",matrxi_A / matrxi_B)

print("\n---\n")

matrix = np.arange(1,13).reshape(3,4)
print("Given matrix :\n",matrix)
print("Sum of rows :",np.sum(matrix,axis = 1))
print("Sum of Columns :",np.sum(matrix,axis = 0))

print("\n---\n")

array = np.array([1,2,3,4,5])
print("Given array :",array)
print("First five elements :",array[:5])
print("Last five elements :",array[-5:])

print("\n---\n")

matrix = np.array([[1,2],
                     [3,4]])
print("Given matrix :\n",matrix)
print("1st Row :",matrix[0:1,:])
print("1st column :\n",matrix[:,0:1])

print("\n---\n")

matrix = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])
print("Given matrix :\n",matrix)
print("1D view :",matrix.ravel())
print("Order changed matrix :\n",matrix.reshape(5,2))

print("\n---\n")

array_1 = np.array([[1,2],
                    [3,4]])
array_2 = np.array([[1,2],
                    [3,4]])
print("Horizontal stacking :",np.hstack([array_1,array_2]))
print("Vertical stacking :\n",np.vstack([array_1,array_2]))
print("--- USING CONCATINATION ---")
print("Horizontal stacking :",np.concatenate([array_1,array_2],axis = 1))
print("Vertical stacking :\n",np.concatenate([array_1,array_2],axis = 0))

print("\n---\n")




---

Given matrix :
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Type : <class 'numpy.ndarray'>

---

Given array : [1 2 3 4 5]
Data type : int64
Given array : [1.5 3.5]
Data type : float64

---

Given angles : [0.   0.22 0.44 0.67 0.89 1.11 1.33 1.56 1.78 2.  ]
Sin values : [0.   0.22 0.43 0.62 0.78 0.9  0.97 1.   0.98 0.91]

---

1D : [0 1 2 3 4 5]
2D :
 [[0 1 2]
 [3 4 5]]
3D :
 [[[0 1 2]
  [3 4 5]]]

---

Addition element-wise :
 [[2 4]
 [6 8]]
Multiplication element-wise :
 [[ 1  4]
 [ 9 16]]
Multiplication matrix :
 [[ 7 10]
 [15 22]]
Division element-wise :
 [[1. 1.]
 [1. 1.]]

---

Given matrix :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum of rows : [10 26 42]
Sum of Columns : [15 18 21 24]

---

Given array : [1 2 3 4 5]
First five elements : [1 2 3 4 5]
Last five elements : [1 2 3 4 5]

---

Given matrix :
 [[1 2]
 [3 4]]
1st Row : [[1 2]]
1st column :
 [[1]
 [3]]

---

Given matrix :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1D view : [ 1  2  3  4  5  6  7  8  

#### 3. Execute all the examples in: https://numpy.org/devdocs/user/absolute_beginners.html

In [53]:
import numpy as np

print("\n---\n")

array = np.array([[1,2,],
                  [3,4]])
print("Given array :\n",array)
print("Shape :",array.shape)

print("\n---\n")

array = np.array([1,2,3,4,5])
print("First element :",array[0])
print("Last element :",array[-1])
print("First 3 elements :",array[2:])
print("Last 3 elements :",array[-3:])

print("\n---\n")

array = np.array([[1,2,],
                  [3,4]])
print("Given array :\n",array)
print("Number of dimensions :",array.ndim)
print("Data type of elements :",array.dtype)

print("\n---\n")

array = np.array([1,2,3,4,5])
print("Given array :",array)
print("Reversed array :",array[::-1])
array.sort()
print("Descending order :",array[::-1])
print("Ascending order :",array)

print("\n---\n")

array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,10])
array_concat = np.concatenate([array_1,array_2])
print("Concatenated array :",array_concat)

print("\n---\n")

array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Given array :",array)
print("Numbers less than 5 :",array[array<5])
print("Even numbers :",array[array%2==0])
print("Odd numbers :",array[array%2!=0])
print("Non zero numbers :",array[array!=0])

print("\n---\n")

array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Given array :",array)
print("Value increased by 10:",array+10)
print("Value decreased by 30:",array-30)
print("Value increased by 1.6:",np.round(array*1.6),3)

print("\n---\n")

array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Given array :",array)
print("Max :",np.max(array))
print("Min :",np.min(array))
print("Sum :",np.sum(array))

print("\n---\n")

matrix = np.random.randint(1,100,size = 3*3).reshape(3,3)
print("Random integer matrix :\n",matrix)
print("Random element :",np.random.choice(np.ravel(matrix)))

print("\n---\n")

matrix = np.random.uniform(0,2,size = 3*3).reshape(3,3)
print("Random float matrix :\n",np.round(matrix,3))
print("Random element :",round(np.random.choice(np.ravel(matrix)),3))

print("\n---\n")

matrix = np.random.randint(1,100,size = 3*3).reshape(3,3)
print("Random integer matrix :\n",matrix)
print("Transpose of matrix :\n",np.transpose(matrix))
print("Determinent : ",round(np.linalg.det(matrix),3))

print("\n---\n")

array = np.array([1,2,3,4,5,6,7,8,9,10])
print("Given array :",array)
print("Reverse array :",array[::-1])

print("\n---\n")

matrix = np.random.randint(1,100,size = 3*3).reshape(3,3)
print("Random integer matrix :\n",matrix)
print("Reversing Rows :\n",matrix[::-1,:])
print("Reversing Columns :\n",matrix[:,::-1])
print("Reversing Rows and Columns :\n",matrix[::-1,::-1])

print("\n---\n")




---

Given array :
 [[1 2]
 [3 4]]
Shape : (2, 2)

---

First element : 1
Last element : 5
First 3 elements : [3 4 5]
Last 3 elements : [3 4 5]

---

Given array :
 [[1 2]
 [3 4]]
Number of dimensions : 2
Data type of elements : int64

---

Given array : [1 2 3 4 5]
Reversed array : [5 4 3 2 1]
Descending order : [5 4 3 2 1]
Ascending order : [1 2 3 4 5]

---

Concatenated array : [ 1  2  3  4  5  6  7  8  9 10]

---

Given array : [ 1  2  3  4  5  6  7  8  9 10]
Numbers less than 5 : [1 2 3 4]
Even numbers : [ 2  4  6  8 10]
Odd numbers : [1 3 5 7 9]
Non zero numbers : [ 1  2  3  4  5  6  7  8  9 10]

---

Given array : [ 1  2  3  4  5  6  7  8  9 10]
Value increased by 10: [11 12 13 14 15 16 17 18 19 20]
Value decreased by 30: [-29 -28 -27 -26 -25 -24 -23 -22 -21 -20]
Value increased by 1.6: [ 2.  3.  5.  6.  8. 10. 11. 13. 14. 16.] 3

---

Given array : [ 1  2  3  4  5  6  7  8  9 10]
Max : 10
Min : 1
Sum : 55

---

Random integer matrix :
 [[98 15 89]
 [50 54 79]
 [ 8  5 32]]
Rand